USE [master]
GO

/****** Object:  Database [CarSell]    Script Date: 17.02.2016 11:08:35 ******/
DROP DATABASE [CarSell]
GO

/****** Object:  Database [CarSell]    Script Date: 17.02.2016 11:08:35 ******/
CREATE DATABASE [CarSell]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarSell', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CarSell.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CarSell_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\CarSell_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CarSell] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarSell].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CarSell] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CarSell] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CarSell] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CarSell] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CarSell] SET ARITHABORT OFF 
GO

ALTER DATABASE [CarSell] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CarSell] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CarSell] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CarSell] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CarSell] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CarSell] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CarSell] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CarSell] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CarSell] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CarSell] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CarSell] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CarSell] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CarSell] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CarSell] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CarSell] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CarSell] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CarSell] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CarSell] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CarSell] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CarSell] SET  MULTI_USER 
GO

ALTER DATABASE [CarSell] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CarSell] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CarSell] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CarSell] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CarSell] SET  READ_WRITE 
GO


